//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAIO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BAIO.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;cn&quot;: {
        ///    &quot;1&quot;: &quot;ÉÁË¸Ø°Ê×ÉèÖÃ&quot;,
        ///    &quot;2&quot;: &quot;µ¥Î»¹ÜÀíÆ÷&quot;,
        ///    &quot;3&quot;: &quot;×Ô¶¯¿¨Î»&quot;,
        ///    &quot;4&quot;: &quot;¿ØÖÆµ¥Î»&quot;,
        ///    &quot;5&quot;: &quot;¿ªÆô&quot;,
        ///    &quot;6&quot;: &quot;Ê¹ÓÃµ¥Î»¼¼ÄÜ&quot;,
        ///    &quot;7&quot;: &quot;Ãô¸Ğ¶È&quot;,
        ///    &quot;8&quot;: &quot;ÊıÖµÔ½´ó,¿¨Î»ÕßµÄÒÆ¶¯·¶Î§¸üĞ¡,¿¨Î»¸ü×¼È·. ÊıÖµÔ½Ğ¡£¬¿¨Î»ÕßµÄÒÆ¶¯·¶Î§Ô½´ó£¬×¼È·¶È¸üµÍ.&quot;,
        ///    &quot;9&quot;: &quot;ÊÇ·ñÊ¹ÓÃÉÁË¸Ø°Ê×£¿&quot;,
        ///    &quot;10&quot;: &quot;ÓÅÏÈÊ¹ÓÃÉÁË¸Ø°Ê×&quot;,
        ///    &quot;11&quot;: &quot;×îĞ¡ÉÁË¸¾àÀë&quot;,
        ///    &quot;12&quot;: &quot;½öµ±×ÔÉíÓëÄ¿±êµĞÈËµÄ¾àÀë´óÓÚ¸ÃÊıÖµµÄÊ±ºò²ÅÊ¹ÓÃÉÁË¸Ø°Ê×&quot;,
        ///    &quot;13&quot;: &quot;ÉÁË¸Î»ÖÃÓëÄ¿±êµĞÈËÖ®¼äµÄ¾àÀë&quot;,
        ///    &quot;14&quot;: &quot;Ê¹ÓÃÉÁË¸Ø°Ê×½«²»»á½Ó½üµĞÈË¸Ã [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cn {
            get {
                return ResourceManager.GetString("cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;en&quot;: {
        ///    &quot;1&quot;: &quot;Blink Menu&quot;,
        ///    &quot;2&quot;: &quot;Unit Controller&quot;,
        ///    &quot;3&quot;: &quot;Bodyblocker&quot;,
        ///    &quot;4&quot;: &quot;Control Units&quot;,
        ///    &quot;5&quot;: &quot;Enabled&quot;,
        ///    &quot;6&quot;: &quot;Use unit abilities&quot;,
        ///    &quot;7&quot;: &quot;Sensitivity&quot;,
        ///    &quot;8&quot;: &quot;Bigger the value, smaller but more accurate block. Smaller the value, bigger but less accurate block.&quot;,
        ///    &quot;9&quot;: &quot;Use blink?&quot;,
        ///    &quot;10&quot;: &quot;Prioritize Blink&quot;,
        ///    &quot;11&quot;: &quot;Minimum Blink Distance&quot;,
        ///    &quot;12&quot;: &quot;Will only use blink if distance to target is bigger than this value&quot;,
        ///    &quot;13&quot;: &quot;Blink Distance  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ru&quot;: {
        ///    &quot;1&quot;: &quot;Blink Menu&quot;,
        ///    &quot;2&quot;: &quot;Unit Controller&quot;,
        ///    &quot;3&quot;: &quot;Bodyblocker&quot;,
        ///    &quot;4&quot;: &quot;Control Units&quot;,
        ///    &quot;5&quot;: &quot;Enabled&quot;,
        ///    &quot;6&quot;: &quot;Use unit abilities&quot;,
        ///    &quot;7&quot;: &quot;Sensitivity&quot;,
        ///    &quot;8&quot;: &quot;Bigger the value, smaller but more accurate block. Smaller the value, bigger but less accurate block.&quot;,
        ///    &quot;9&quot;: &quot;Use blink?&quot;,
        ///    &quot;10&quot;: &quot;Prioritize Blink&quot;,
        ///    &quot;11&quot;: &quot;Minimum Blink Distance&quot;,
        ///    &quot;12&quot;: &quot;Will only use blink if distance to target is bigger than this value&quot;,
        ///    &quot;13&quot;: &quot;Blink Distance  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
    }
}
